### ISSUE TITLE
publish the package to conda-forge

### ISSUE THREAD

**Issue by 12rambau** [smarie/python-yamlable#19]
I'm relying on this package in a conda-forge recipe and it breaks as it's not available there. Would you consider publishing it on conda-forge ? 

I can do it for you, you will just need to agree to be set admin of the feedstock.

**Comment by smarie** [comment]
Hi @12rambau , if you need it yes - sure. I am already doing it for `pytest-cases` (https://github.com/conda-forge/pytest-cases-feedstock), I will know how to manage the updates - but I'd appreciate that you do the initial setup, thanks for proposing it !
