### ISSUE TITLE
pip installation fail: Exception: Required packages for setup not found. Please install `setuptools_scm`

### ISSUE THREAD

**Issue by ALERTua** [smarie/python-yamlable#9]
Hey. I'd love to use your package but I have no luck installing it.
![image](https://user-images.githubusercontent.com/8375129/66408093-f8fbf800-e9f6-11e9-8edb-0a977858a655.png)
![image](https://user-images.githubusercontent.com/8375129/66407964-c0f4b500-e9f6-11e9-985f-54b56beb80a9.png)
@ Python 2.7, latest pip&setuptools, latest PyCharm

**Comment by smarie** [comment]
Did you try installing `setuptools_scm` as mentioned ?

**Comment by ALERTua** [comment]
oh. I didn't find such a module among PyCharm pip search results and didn't try installing it via pip install.
![image](https://user-images.githubusercontent.com/8375129/66414094-62810400-ea01-11e9-8e35-970fc9bb8091.png)
The manual installation succeeded.
![image](https://user-images.githubusercontent.com/8375129/66414149-804e6900-ea01-11e9-89b7-5fb70f614798.png)

Sorry, my bad.

**Comment by smarie** [comment]
Perfect, thanks for the feedback !
